apiVersion: pingcap.com/v1alpha1
kind: IoChaos
metadata:
  name: mixed
  namespace: {chaos_namespace}
spec:
  action: mixed
  mode: one
  duration: "400s"
  configName: "chaosfs-tiflash"
  path: ""
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      "app": "tiflash"
  layer: "fs"
  percent: "50"
  delay: "1ms"
  scheduler:
    cron: "@every 10m"
