apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: partition-tikv
  namespace: {chaos_namespace}
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  direction: to
  target:
    selector:
      namespaces:
        - {namespace}
      labelSelectors:
        "app": "tiflash"
    mode: all
  duration: "10s"
  scheduler:
    cron: "@every 15s"
    