apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: delay-tikv
  namespace: {chaos_namespace}
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  delay:
    latency: "2000ms"
    correlation: "1"
    jitter: "100ms"
  duration: "20s"
  scheduler:
    cron: "@every 40s"
    