apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: loss-tikv
  namespace: {chaos_namespace}
spec:
  action: loss
  mode: one
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  loss:
    loss: "25"
    correlation: "25"
  duration: "10s"
  scheduler:
    cron: "@every 15s"
