apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: tidb-failure
  namespace: {chaos_namespace}
spec:
  action: pod-failure
  mode: one
  duration: "30s"
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      "app.kubernetes.io/component": "tidb"
  scheduler:
    cron: "@every 2m"
