apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: kill
  namespace: {chaos_namespace}
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - {namespace}
    labelSelectors:
      "app": "tiflash"
  scheduler:
    cron: "@every 5m"
