apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: test-tiflash-pd-d
  namespace: tiflash-chaos
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - test-tiflash
    labelSelectors:
      "app.kubernetes.io/component": "pd"
  delay:
    latency: "2000ms"
    correlation: "1"
    jitter: "100ms"
  duration: "20s"
  scheduler:
    cron: "@every 40s"
   
